// template: { name: "", role: "", img: "img-japan/", school: "", bonds: [] },
const characters = [
    { name: "Hinata SP", role: "MB", img: "img-japan/hinataSP.png", school: "Karasuno", bonds: ["Similar Builds","Weird Duo (Hanami)",] },
    { name: "Hinata SSR", role: "MB", img: "img-japan/hinataSSR.png", school: "Karasuno", bonds: ["Flexible Aces", "Worthy Rival", "Surprising Friendship","Rival Friends","Weird Duo","Karasuno's Failing Grades Group"] },
    { name: "Hinata SR", role: "MB", img: "img-japan/hinataSR.png", school: "Karasuno", bonds: ["Teammates on the Court","\"Sun\" and \"Moon\"",] },
    { name: "Kageyama UR", role: "S", img: "img-japan/tobioUR.png", school: "Karasuno", bonds: ["Weird Duo","The King and The Great King","Karasuno's Setters","Karasuno's Failing Grades Group","Weird Duo (Hanami)"] },
    { name: "Kageyama SSR", role: "S", img: "img-japan/tobioSSR.png", school: "Karasuno", bonds: ["Teammates on the Court","Building Team Chemistry"] },
    { name: "Daichi SSR", role: "OP", img: "img-japan/daichiSSR.png", school: "Karasuno", bonds: ["Karasuno\'s Pillar","karasuno Senior Year","Behind the Smile"] },
    { name: "Daichi SR", role: "OP", img: "img-japan/daichiSR.png", school: "Karasuno", bonds: ["Karasuno\'s Pillar(practice)","Leaders Cut from the Same Cloth"] },
    { name: "Sugawara SP", role: "S", img: "img-japan/sugawaraSP.png", school: "Karasuno", bonds: [] },
    { name: "Sugawara SR", role: "S", img: "img-japan/sugawaraSR.png", school: "Karasuno", bonds: ["karasuno Senior Year","Karasuno's Setters",] },
    { name: "Asahi SSR", role: "WS", img: "img-japan/asahiSSR.png", school: "Karasuno", bonds: ["karasuno Senior Year","\"Guardian Deity\" and \"Wing Spiker\"","Cannon \& Iron Wall"] },
    { name: "Asahi SR", role: "WS", img: "img-japan/asahiSR.png", school: "Karasuno", bonds: ["\"Guardian Deity\" and \"Ace\"","Karasuno\'s Wing Spiker"] },
    { name: "Nishinoya SP", role: "Li", img: "img-japan/nishinoyaSP.png", school: "Karasuno", bonds: [] },
    { name: "Nishinoya SSR", role: "Li", img: "img-japan/nishinoyaSSR.png", school: "Karasuno", bonds: ["Karasuno\'s sophomore", "Kiyoko\'s Knights","\"Guardian Deity\" and \"Wing Spiker\"","Karasuno's Failing Grades Group","Team's Guardians"] },
    { name: "Nishinoya SR", role: "Li", img: "img-japan/nishinoyaSR.png", school: "Karasuno", bonds: ["\"Guardian Deity\" and \"Ace\"","Formidable Opponent","Karasuno\'s Sophomore(practice)"] },
    { name: "Tanaka SSR", role: "WS", img: "img-japan/tanakaSSR.png", school: "Karasuno", bonds: ["Karasuno\'s sophomore", "Kiyoko\'s Knights","TOMODACHI(Friends!)","Karasuno's Failing Grades Group"] },
    { name: "Tanaka SR", role: "WS", img: "img-japan/tanakaSR.png", school: "Karasuno", bonds: ["Karasuno\'s Wing Spiker","Building Team Chemistry","Karasuno\'s Sophomore(practice)"] },
    { name: "Tsukishima SP", role: "MB", img: "img-japan/tsukishimaSP.png", school: "Karasuno", bonds: [] },
    { name: "Tsukishima SSR", role: "MB", img: "img-japan/tsukishimaSSR.png", school: "Karasuno", bonds: ["\"Shield\" and \"Spear\"","Master and Apprentice","Prediction VS System"] },
    { name: "Tsukishima SR", role: "MB", img: "img-japan/tsukishimaSR.png", school: "Karasuno", bonds: ["Simulated Junior Training Teamate","\"Shield\" and \"Spear\"(practice)","\"Sun\" and \"Moon\""] },
    { name: "Tadashi SR", role: "MB", img: "img-japan/tadashiSR.png", school: "Karasuno", bonds: ["\"Shield\" and \"Spear\"",] },
    { name: "Tadashi R", role: "MB", img: "img-japan/tadashiR.png", school: "Karasuno", bonds: ["\"Shield\" and \"Spear\"(practice)"] },
    { name: "Chikara SR", role: "WS", img: "img-japan/chikaraSR.png", school: "Karasuno", bonds: ["Karasuno\'s sophomore", "Karasuno\'s Pillar","The Returning Trio"] },
    { name: "Chikara R", role: "WS", img: "img-japan/chikaraR.png", school: "Karasuno", bonds: ["Karasuno\'s Wing Spiker","Karasuno\'s Pillar(practice)","Karasuno\'s Sophomore(practice)"] },
    { name: "Hisashi R", role: "WS", img: "img-japan/hisashiR.png", school: "Karasuno", bonds: ["Bench cheer","The Returning Trio"] },
    { name: "Kazuhito R", role: "MB", img: "img-japan/kazuhitoR.png", school: "Karasuno", bonds: ["Bench cheer","The Returning Trio"] },
    { name: "Kageyama SR", role: "S", img: "img-japan/tobioSR.png", school: "Kitagawa", bonds: [] },

    { name: "Oikawa UR", role: "S", img: "img-japan/oikawaUR.png", school: "Aoba Johsai", bonds: ["The King and The Great King"] },
    { name: "Oikawa SSR", role: "S", img: "img-japan/oikawaSSR.png", school: "Aoba Johsai", bonds: ["Team Chemistry"] },
    { name: "Iwaizumi SSR", role: "WS", img: "img-japan/iwaizumiSSR.png", school: "Aoba Johsai", bonds: ["The Wolf Pack"] },
    { name: "Iwaizumi SR", role: "WS", img: "img-japan/iwaizumiSR.png", school: "Aoba Johsai", bonds: ["The Wolf Pack(Practice)","Team Chemistry"] },
    { name: "Matsukawa SR", role: "MB", img: "img-japan/matsukawaSR.png", school: "Aoba Johsai", bonds: ["Seijoh\'s Senior Year Pillars"] },
    { name: "Hanamaki SR", role: "WS", img: "img-japan/hanamakiSR.png", school: "Aoba Johsai", bonds: ["Seijoh\'s Senior Year Pillars"] },
    { name: "Yahaba SR", role: "S", img: "img-japan/yahabaSR.png", school: "Aoba Johsai", bonds: ["Aoba Johsai's Sophomore","Hidden Fire"] },
    { name: "Watari SR", role: "Li", img: "img-japan/watariSR.png", school: "Aoba Johsai", bonds: ["Aoba Johsai's Sophomore"] },
    { name: "Kindaichi SR", role: "MB", img: "img-japan/kindaichiSR.png", school: "Aoba Johsai", bonds: ["Blunt and Composed"] },
    { name: "Kunimi SR", role: "OP", img: "img-japan/kunimiSR.png", school: "Aoba Johsai", bonds: ["Blunt and Composed"] },
    { name: "Kentaro SSR", role: "OP", img: "img-japan/kyotaniSSR.png", school: "Aoba Johsai", bonds: ["Aoba Johsai's Sophomore","Hidden Fire","The Wolf Pack"] },
    { name: "Kentaro SR", role: "OP", img: "img-japan/kyotaniSR.png", school: "Aoba Johsai", bonds: ["The Wolf Pack(Practice)"] },

    { name: "Kenma SP", role: "S", img: "img-japan/kenmaSP.png", school: "Nekoma", bonds: [] },
    { name: "Kenma SSR", role: "S", img: "img-japan/kenmaSSR.png", school: "Nekoma", bonds: ["Rival Friends","\"Brain\" and \"Control Tower\"","Grit and Competitive","The \"Enigmatic\" Teammate"] },
    { name: "Kenma SR", role: "S", img: "img-japan/kenmaSR.png", school: "Nekoma", bonds: ["\"Pivot\" and \"Defensive Pivot\"","\"Pivot\" and \"Control Tower\""] },
    { name: "Kuroo UR", role: "MB", img: "img-japan/kurooUR.png", school: "Nekoma", bonds: ["Behind the Smile","Master and Apprentice","\"Brain\" and \"Control Tower\""] },
    { name: "Kuroo SSR", role: "MB", img: "img-japan/kurooSSR.png", school: "Nekoma", bonds: ["Leaders Cut from the Same Cloth","\"Pivot\" and \"Control Tower\""] },
    { name: "Yaku SR", role: "Li", img: "img-japan/yakuSR.png", school: "Nekoma", bonds: ["Formidable Opponent","One-on-One Training","\"Pivot\" and \"Defensive Pivot\""] },
    { name: "Yaku SSR", role: "Li", img: "img-japan/yakuSSR.png", school: "Nekoma", bonds: ["Team's Guardians"] },
    { name: "Lev SSR", role: "MB", img: "img-japan/levSSR.png", school: "Nekoma", bonds: ["Flexible Aces","Nekoma\'s Junior","The \"Enigmatic\" Teammate"] },
    { name: "Lev SR", role: "MB", img: "img-japan/levSR.png", school: "Nekoma", bonds: ["One-on-One Training"] },
    { name: "Yamamoto SR", role: "WS", img: "img-japan/yamamotoSR.png", school: "Nekoma", bonds: ["TOMODACHI(Friends!)","Nekoma\'s Wing Spiker","Grit and Competitive"] },
    { name: "Kai SR", role: "OP", img: "img-japan/kaiSR.png", school: "Nekoma", bonds: ["Nekoma\'s Wing Spiker"] },
    { name: "Fukunaga SR", role: "WS", img: "img-japan/fukunagaSR.png", school: "Nekoma", bonds: ["Nekoma\'s Wing Spiker"] },
    { name: "Inuoka SR", role: "MB", img: "img-japan/inuokaSR.png", school: "Nekoma", bonds: ["Worthy Rival","Nekoma\'s Junior"] },
    { name: "Teshiro SR", role: "S", img: "img-japan/teshiroSR.png", school: "Nekoma", bonds: ["Nekoma\'s Junior"] },

    { name: "Aone SP", role: "MB", img: "img-japan/aoneSP.png", school: "Date Kogyo", bonds: [] },
    { name: "Aone SSR", role: "MB", img: "img-japan/aoneSSR.png", school: "Date Kogyo", bonds: ["Cannon \& Iron Wall","Surprising Friendship","The Silent and the Snarky"] },
    { name: "Aone SR", role: "MB", img: "img-japan/aoneSR.png", school: "Date Kogyo", bonds: [] },
    { name: "Kenji SSR", role: "WS", img: "img-japan/kenjiSSR.png", school: "Date Kogyo", bonds: ["Date Kogyo\'s Captains","The Silent and the Snarky","New Captain \& Tall Rookie"] },
    { name: "Kenji SR", role: "WS", img: "img-japan/kenjiSR.png", school: "Date Kogyo", bonds: [] },
    { name: "Kanji SSR", role: "S", img: "img-japan/kanjiSSR.png", school: "Date Kogyo", bonds: ["New Captain \& Tall Rookie","Date Kogyo\'s Setter",] },
    { name: "Kanji SR", role: "S", img: "img-japan/kanjiSR.png", school: "Date Kogyo", bonds: ["Simulated Junior Training Teamate"] },
    { name: "Sakunami R", role: "Li", img: "img-japan/sakunamiR.png", school: "Date Kogyo", bonds: ["Date Kogyo\'s Junior"] },
    { name: "Kamasaki SR", role: "MB", img: "img-japan/kamasakiSR.png", school: "Date Kogyo", bonds: ["Date Kogyo\'s Senior"] },
    { name: "Kaname SR", role: "S", img: "img-japan/kanameSR.png", school: "Date Kogyo", bonds: ["Date Kogyo\'s Captains","Date Kogyo\'s Setter","Date Kogyo\'s Senior",] },
    { name: "Sasaya SSR", role: "OP", img: "img-japan/takehitoSSR.png", school: "Date Kogyo", bonds: ["Date Kogyo\'s Wing Spiker","Date Kogyo\'s Senior"] },
    { name: "Sasaya SR", role: "OP", img: "img-japan/takehitoSR.png", school: "Date Kogyo", bonds: [] },
    { name: "Yutaka SR", role: "WS", img: "img-japan/yutakaSR.png", school: "Date Kogyo", bonds: ["Date Kogyo\'s Wing Spiker"] },
    { name: "Jingo R", role: "MB", img: "img-japan/jingoR.png", school: "Date Kogyo", bonds: ["Date Kogyo\'s Junior"] },
    { name: "Taro R", role: "OP", img: "img-japan/taroR.png", school: "Date Kogyo", bonds: [] },

    { name: "Ushijima UR", role: "OP", img: "img-japan/ushijimaUR.png", school: "Shiratorizawa", bonds: ["Lifelong Best Friends","Undisputed Aces"] },
    { name: "Goshiki SSR", role: "WS", img: "img-japan/goshikiSSR.png", school: "Shiratorizawa", bonds: ["Promising Senpai","Undisputed Aces"] },
    { name: "Tendo SSR", role: "MB", img: "img-japan/tendoSSR.png", school: "Shiratorizawa", bonds: ["Lifelong Best Friends","Promising Senpai","Shiratorizawa\'s Middke Blocker","Prediction VS System"] },
    { name: "Taichi SR", role: "MB", img: "img-japan/kawanishiSR.png", school: "Shiratorizawa", bonds: ["Shiratorizawa\'s Middke Blocker"] },
    { name: "Shirabu SSR", role: "S", img: "img-japan/kenjiroSSR.png",school: "Shiratorizawa", bonds: [] },
    { name: "Semi SSR", role: "S", img: "img-japan/semiSSR.png",school: "Shiratorizawa", bonds: [] },
    { name: "Ohira SSR", role: "WS", img: "img-japan/ohiraSSR.png",school: "Shiratorizawa", bonds: [] },
    { name: "Yamagata SSR", role: "Li", img: "img-japan/yamagataSSR.png",school: "Shiratorizawa", bonds: [] },

    { name: "Bokuto SP", role: "WS", img: "img-japan/bokutoSP.png",school: "Fukurodani", bonds: [] },
    { name: "Bokuto UR", role: "WS", img: "img-japan/bokutoUR.png",school: "Fukurodani", bonds: [] },
    { name: "Akaashi SP", role: "S", img: "img-japan/akaashiSP.png",school: "Fukurodani", bonds: [] },
    { name: "Akaashi SSR", role: "S", img: "img-japan/akaashiSSR.png",school: "Fukurodani", bonds: [] },
    { name: "Konoha SSR", role: "OP", img: "img-japan/konohaSSR.png",school: "Fukurodani", bonds: [] },
    { name: "Sarukui SSR", role: "Li", img: "img-japan/sarukuiSSR.png",school: "Fukurodani", bonds: [] },
    { name: "Komi SR", role: "WS", img: "img-japan/komiSR.png",school: "Fukurodani", bonds: [] },
    { name: "Onaga R", role: "MB", img: "img-japan/onagaR.png",school: "Fukurodani", bonds: [] },
    { name: "Washio SSR", role: "MB", img: "img-japan/washioSSR.png",school: "Fukurodani", bonds: [] },

    { name: "Terushima SSR", role: "WS", img: "img-japan/terushimaSSR.png",school: "Johzenji", bonds: [] },
    { name: "Bobata R", role: "MB", img: "img-japan/bobataR.png",school: "Johzenji", bonds: [] },
    { name: "Futamata SR", role: "S", img: "img-japan/futamataSR.png",school: "Johzenji", bonds: [] },
    { name: "Higashiyama SR", role: "WS", img: "img-japan/higashiyamaSR.png",school: "Johzenji", bonds: [] },
    { name: "Izaka R", role: "MB", img: "img-japan/izakaR.png",school: "Johzenji", bonds: [] },
    { name: "Numajiri R", role: "OP", img: "img-japan/numajiriR.png",school: "Johzenji", bonds: [] },
    { name: "Tsuchiyu R", role: "Li", img: "img-japan/tsuchiyuR.png",school: "Johzenji", bonds: [] },

    { name: "Kita SSR", role: "WS", img: "img-japan/kitaSSR.png",school: "Inarizaki", bonds: [] },
    { name: "Omimi SR", role: "MB", img: "img-japan/omimiSR.png",school: "Inarizaki", bonds: [] },
    { name: "Ojiro SSR", role: "WS", img: "img-japan/ojiroSSR.png",school: "Inarizaki", bonds: [] },
    { name: "Ginjima SSR", role: "WS", img: "img-japan/ginjimaSSR.png",school: "Inarizaki", bonds: [] },
    { name: "Atsumu UR", role: "S", img: "img-japan/atsumuUR.png",school: "Inarizaki", bonds: [] },
    { name: "Suna SSR", role: "MB", img: "img-japan/sunaSSR.png",school: "Inarizaki", bonds: [] },
    { name: "Osamu UR", role: "MB", img: "img-japan/osamuUR.png",school: "Inarizaki", bonds: [] },
    { name: "Kosaku R", role: "WS", img: "img-japan/kosakuR.png",school: "Inarizaki", bonds: [] },
    { name: "Riseki R", role: "WS", img: "img-japan/risekiR.png",school: "Inarizaki", bonds: [] },
    { name: "Akagi SSR", role: "WS", img: "img-japan/akagiSSR.png",school: "Inarizaki", bonds: [] },
   
    { name: "Hoshiumi UR", role: "WS", img: "img-japan/hoshiumiUR.png",school: "Inarizaki", bonds: ["Similar Builds"] },
    { name: "Hirugami UR", role: "MB", img: "img-japan/hirugamiUR.png",school: "Inarizaki", bonds: [] },

    { name: "Sakusa UR", role: "WS", img: "img-japan/sakusaUR.png",school: "Inarizaki", bonds: [] },
    { name: "Komori UR", role: "Li", img: "img-japan/komoriUR.png",school: "Inarizaki", bonds: [] },

];
// tempalte: "": "",
const synergyDescriptions = {
    "Karasuno": "Increases Power Attack and Quick Attack stats of all players present by 10%",
    "Shiratorizawa": "Increases Awareness and Strength of all players present by 10%",
    "Aoba Johsai": "Increases Power Attack stats of all players present by 15%",
    "Nekoma": "Increases Receive stat of all players present by 15%",
    "Date Kogyo": "Increases Block stat of all players present by 15%",

    //karasuno bond
    "Karasuno\'s Pillar": "When achieving a PERFECT receive, increases Team Morale by 3/3/4/4/5",
    "Flexible Aces": { "Hinata SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%", "Lev SSR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%"},
    "Worthy Rival": {"Hinata SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Inuoka SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},
    "Kiyoko\'s Knights": "When scoring, increases Team morale by 6/7/8/9/10",
    "karasuno Senior Year": "Reduces Stamina consumption of Spike skills by 10%; when performing Power Spikes, increases this player\'s Attack Technique by 6/7/8/9/10%",
    "\"Guardian Deity\" and \"Wing Spiker\"": "When Nishinoya or Asahi casts a skill, increases their Attack Technique and Defense Technique by 6/7/8/9/10%",
    "\"Shield\" and \"Spear\"":"Increases Tsukishima\'s Block stat by 6/7/8/9/10% and Tadashi\'s Serve stat by 6/7/8/9/10%",
    "TOMODACHI(Friends!)":{"Yamamoto SR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%","Tanaka SSR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "Cannon \& Iron Wall": {"Asahi SSR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%","Aone SSR":"No buff"},
    "Karasuno\'s sophomore": {"Chikara SR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%", "Nishinoya SSR": "Set +5/7/9/12/15, Set +1/2/3/4/5%", "Tanaka SSR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "\"Guardian Deity\" and \"Ace\"":"When Nishinoya or Asahi casts a skill, increases their Attack Technique by 6/7/8/9/10%",
    "Leaders Cut from the Same Cloth": {"Daichi SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Kuroo SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Surprising Friendship":{"Aone SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Hinata SSR":"No buff"},
    "Karasuno\'s Wing Spiker":{"Tanaka SR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%", "Asahi SR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%", "Chikara SR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "Teammates on the Court": "When casting Quick Spike skills, increases this player's Awareness ny 6/7/8/9/10%",
    "Simulated Junior Training Teamate": {"Kanji SR":"Set +5/7/9/12/15, Set +1/2/3/4/5%","Tsukishima SR": "No buff"},
    "Karasuno\'s Pillar(practice)": {"Chikara R": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Daichi SR":"Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "\"Shield\" and \"Spear\"(practice)": "Increases Tsukishima\'s Block stat by 6/7/8/9/10% and Tadashi\'s Serve stat by 6/7/8/9/10%",
    "Formidable Opponent": {"Nishinoya SR":" Save +5/7/9/12/15, Save +1/2/3/4/5%","Yaku SR":" Set +5/7/9/12/15, Set +1/2/3/4/5%"},
    "Bench cheer" : {"Hisashi R": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%", "Kazuhito R": "Block +5/7/9/12/15, Block +1/2/3/4/5%" },
    "The Returning Trio":{"Hisashi R":"Set +5/7/9/12/15, Set +1/2/3/4/5%","Kazuhito R":"Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%","Chikara SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},
    "\"Sun\" and \"Moon\"": {"Tsukishima SR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%", "Hinata SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%" },
    "Building Team Chemistry": {"Kageyama SSR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%", "Tanaka SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%" },
    "Karasuno\'s Sophomore(practice)":"Increases Receive stat of back row players 6/7/8/9/10%",
    "Rival Friends": {"Hinata SSR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%", "Kenma SSR": "Set +5/7/9/12/15, Set +1/2/3/4/5%" },
    "Behind the Smile": {"Daichi SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Kuroo UR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%" },
    "Master and Apprentice": {"Tsukishima SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Kuroo UR": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Weird Duo": "Hinata performs a Quick Attack with 280/295/310/325/340% Speed. Awareness +30%, Power +(Awareness ×30/35/40/45/50%, max 60/70/80/90/100%). Cannot be blocked. Resets cooldown on scoring.",
    "The King and The Great King": {"Kageyama UR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%","Oikawa UR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%"},
    "Karasuno's Setters": {"Kageyama": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%","Sugawara": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%"},
    "Karasuno's Failing Grades Group": {"Hinata SSR": "","Kageyama UR": "","Nishinoya SSR": "","Tanaka SSR": "Strong Attack +5/7/9/12/15, Strong Attack +1/2/3/4/5%"},
    "Team's Guardians": {"Nishinoya SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Yaku SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},
    "Similar Builds": {"Hinata (Hanami)": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%","Hoshiumi": "Strong Attack +5/7/9/12/15, Strong Attack +1/2/3/4/5%"},
    "Weird Duo (Hanami)": "When an ally uses a Receive skill, consumes 1 [Never Give Up] stack to increase their Reaction by 6%. If Hinata (Hanami) uses Receive, his Reaction increases by an additional 9% and Kageyama gains 1 stack of [Never Give Up]. Hinata (Hanami)'s Special also grants Kageyama 1 stack of [Never Give Up].",

    //Aoba Johsai
    "Aoba Johsai's Sophomore": {"Watari SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Yahaba SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Kentaro SSR": "No buff" },
    "Blunt and Composed":"Increases Kindaichi\'s Quick Attack stat by 6/7/8/9/10% and  Kunimi\'s Power Attack stat by 6/7/8/9/10%",
    "The Wolf Pack":"Increases  Iwaizumi and Kentaro\'s Power Attack stat by 6/7/8/9/10%",
    "Hidden Fire":{"Kentaro SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Yahaba SR": "No buff"},
    "Seijoh\'s Senior Year Pillars": "Increases Matsukawa\'s Block stat by 6/67/8/9/10% and Hanamaki\'s Receive stat by 6/7/8/9/10%",
    "The Wolf Pack(Practice)": "Increases Iwaisumi and Kentaro's Awareness by 6/7/8/9/10%",
    "Team Chemistry" : "Increases Oikawa and Iwaizumi's Awareness by 6/7/8/9/10%",

    //Nekoma
    "Nekoma\'s Junior":{"Teshiro SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Inuoka SR": "No buff", "Lev SSR":"No Buff"},
    "\"Brain\" and \"Control Tower\"":"Kenma sets the ball, Kuroo performs a Quick Spike with 265/280/295/310/325% of Quick Attack stat as power",
    "Nekoma\'s Wing Spiker":"Increases Receive and Power Attack stats of players present by 4/5/6/7/8%",
    "Grit and Competitive":{"Yamamoto SR": "No buff","Kenma SSR": "Set +5/7/9/12/15, Set +1/2/3/4/5%"},
    "One-on-One Training":{"Lev SR": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Yaku SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},
    "The \"Enigmatic\" Teammate":{"Lev SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Kenma SSR": "No buff"},
    "\"Pivot\" and \"Defensive Pivot\"":{"Yaku SR": "Save +5/7/9/12/15, Save +1/2/3/4/5%","Kenma SSR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "\"Pivot\" and \"Control Tower\"":"Increases Kenma\'s Set stat by 6/7/8/9/10% and Kuroo\'s Block Stat by 6/7/8/9/10%",

    //Date Kogyo
    "Date Kogyo\'s Captains":{"Kaname SR":"No buff","Kenji SSR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "The Silent and the Snarky":"Aone and Kenji perform a Double block with 180/195/210/225/240% of Aone\'s Block stat as power;applies \"Enrage\" Debuff to opponent spiker \(reduces Power\/Quick Attack stats by 10%\)",
    "New Captain \& Tall Rookie":"Increases Block stat of front row players by 2/2.5/3/3.5/4%",
    "Date Kogyo\'s Wing Spiker":"Increases Yutaka\'s Block stat by 2/2.5/3/3.5/4% and Takehito\'s Power Attack stat by 2/2.5/3/3.5/4%",
    "Date Kogyo\'s Setter":{"KanameSR":"No buff","Kaji SSR":"Set +5/7/9/12/15, Set +1/2/3/4/5%"},
    "Date Kogyo\'s Junior":{"Jingo R":"Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Sakunami R":"Quick Attack +5/7/9/12/15, Quick Attack stat by 6/7/8/9/10%"},
    "Date Kogyo\'s Senior": "When casting Block skills, increases Team morale by 3/3/4/4/5",

    //Shiratorizawa
    "Lifelong Best Friends":"Increases Ushijima\'s Attack Technique by 3/3.5/4/4.5/5% and Tendo\'s Defense Technique by 3/3.5/4/4.5/5%",
    "Promising Senpai":{"Tendo SSR":"Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%","Goshiki SSR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "Undisputed Aces":{"Goshiki SSR":"Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Ushijima UR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "Shiratorizawa\'s Middke Blocker":"Increases Block stat of your side\'s front row players by 5/5.5/6/6.5/7%",
    "Prediction VS System":{"Tsukishima SSR":"No buff","Tendo SSR":"Block +5/7/9/12/15, Block +1/2/3/4/5%"},

};

//Lowkey just have to remeber that when a bond is create I put it here
//template: "": { category: "school| stats|deployement", activation: { scope: "starters|any", min:  } },
const synergyMeta = {
    "Karasuno": { category: "school", activation: { scope: "starters", min: 4 } },
    "Shiratorizawa": { category: "school", activation: { scope: "starters", min: 4 } },
    "Aoba Johsai": { category: "school", activation: { scope: "starters", min: 4 } },
    "Nekoma": { category: "school", activation: { scope: "starters", min: 4 } },
    "Date Kogyo": { category: "school", activation: { scope: "starters", min: 4 } },

    "Karasuno\'s Pillar": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Flexible Aces": { category: "stats", activation: { scope: "any", min: 2 } },
    "Worthy Rival": { category: "stats", activation: { scope: "any", min: 2 } },
    "Kiyoko\'s Knights": { category: "deployment", activation: { scope: "any", min: 2 } },
    "karasuno Senior Year": { category: "deployment", activation: { scope: "any", min: 3 } },
    "\"Guardian Deity\" and \"Wing Spiker\"":{ category: "deployment", activation: { scope: "any", min: 2 } },
    "\"Shield\" and \"Spear\" (practice)":{ category: "deployment", activation: { scope: "any", min: 2 } },
    "TOMODACHI(Friends!)":{ category: "stats", activation: { scope: "any", min: 2 } },
    "Cannon \& Iron Wall":{ category: "stats", activation: { scope: "any", min: 2 } },
    "Karasuno\'s sophomore": { category: "stats", activation: { scope: "any", min: 3 } },
    "\"Guardian Deity\" and \"Ace\"": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Leaders Cut from the Same Cloth": { category: "stats", activation: { scope: "any", min: 2 } },
    "Surprising Friendship": { category: "stats", activation: { scope: "any", min: 2 } },
    "Karasuno\'s Wing Spiker": { category: "stats", activation: { scope: "any", min: 3 } },
    "Teammates on the Court": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Simulated Junior Training Teamate": { category: "stats", activation: { scope: "any", min: 2 } },
    "Karasuno\'s Pillar(practice)": { category: "stats", activation: { scope: "any", min: 2 } },
    "\"Shield\" and \"Spear\"(practice)": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Formidable Opponent": { category: "stats", activation: { scope: "any", min: 2 } },
    "Bench cheer": { category: "stats", activation: { scope: "any", min: 2 } },
    "The Returning Trio": { category: "stats", activation: { scope: "any", min: 3 } },
    "\"Sun\" and \"Moon\"": { category: "stats", activation: { scope: "any", min: 2 } },
    "Building Team Chemistry": { category: "stats", activation: { scope: "any", min: 2 } },
    "Karasuno\'s Sophomore(practice)": { category: "deployment", activation: { scope: "any", min: 3 } },
    "Rival Friends": { category: "stats", activation: { scope: "any", min: 2 } },
    "Behind the Smile": { category: "stats", activation: { scope: "any", min: 2 } },
    "Master and Apprentice": { category: "stats", activation: { scope: "any", min: 2 } },
    "Weird Duo": { category: "deployment", activation: { scope: "any", min: 2 } },
    "The King and The Great King": { category: "stats", activation: { scope: "any", min: 2 } },
    "Karasuno's Setters": { category: "stats", activation: { scope: "any", min: 2 } },
    "Karasuno's Failing Grades Group": { category: "stats", activation: { scope: "any", min: 4 } },
    "Team's Guardians": { category: "stats", activation: { scope: "any", min: 2 } },
    "Similar Builds": { category: "stats", activation: { scope: "pair", min: 2 } },
    "Weird Duo (Hanami)": { category: "special", activation: { scope: "pair", min: 2 } },
    
    "Aoba Johsai's Sophomore": { category: "stats", activation: { scope: "any", min: 3 } },
    "Blunt and Composed": { category: "deployment", activation: { scope: "any", min: 2 } },
    "The Wolf Pack": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Hidden Fire":{ category: "stats", activation: { scope: "any", min: 2 } },
    "Seijoh\'s Senior Year Pillars": { category: "deployment", activation: { scope: "any", min: 2 } },
    "The Wolf Pack(Practice)": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Team Chemistry": { category: "deployment", activation: { scope: "any", min: 2 } },

    "Nekoma\'s Junior": { category: "stats", activation: { scope: "any", min: 3 } },
    "\"Brain\" and \"Control Tower\"": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Nekoma\'s Wing Spiker": { category: "deployment", activation: { scope: "any", min: 3 } },
    "Grit and Competitive": { category: "stats", activation: { scope: "any", min: 2 } },
    "One-on-One Training": { category: "stats", activation: { scope: "any", min: 2 } },
    "The \"Enigmatic\" Teammate": { category: "stats", activation: { scope: "any", min: 2 } },
    "\"Pivot\" and \"Defensive Pivot\"": { category: "stats", activation: { scope: "any", min: 2 } },
    "\"Pivot\" and \"Control Tower\"": { category: "deployment", activation: { scope: "any", min: 2 } },

    "Date Kogyo\'s Captains": { category: "stats", activation: { scope: "any", min: 2 } },
    "The Silent and the Snarky": { category: "deployment", activation: { scope: "any", min: 2 } },
    "New Captain \& Tall Rookie": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Date Kogyo\'s Wing Spiker": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Date Kogyo\'s Setter": { category: "stats", activation: { scope: "any", min: 2 } },
    "Date Kogyo\'s Junior": { category: "stats", activation: { scope: "any", min: 2 } },
    "Date Kogyo\'s Senior": { category: "deployment", activation: { scope: "any", min: 3 } },

    "Lifelong Best Friends":{ category: "deployment", activation: { scope: "any", min: 2 } },
    "Promising Senpai":{ category: "stats", activation: { scope: "any", min: 2 } },
    "Undisputed Aces":{ category: "stats", activation: { scope: "any", min: 2 } },
    "Shiratorizawa\'s Middke Blocker":{ category: "deployment", activation: { scope: "any", min: 2 } },
    "Prediction VS System":{ category: "stats", activation: { scope: "any", min: 2 } },

};

//put what player create the bond
const synergyPairs = {
    "Karasuno\'s Pillar": [["Chikara", "Daichi"]],
    "Flexible Aces": [["Hinata", "Lev"]],
    "Worthy Rival": [["Hinata", "Inuoka"]],
    "Kiyoko\'s Knights": [["Tanaka", "Nishinoya"]],
    "karasuno Senior Year": [["Daichi", "Sugawara", "Asahi"]],
    "\"Guardian Deity\" and \"Wing Spiker\"": [["Nishinoya", "Asahi"]],
    "\"Shield\" and \"Spear\"": [["Tsukishima", "Tadashi"]],
    "TOMODACHI(Friends!)":[["Tanaka","Yamamoto"]],
    "Cannon \& Iron Wall":[["Asahi", "Aone"]],
    "Karasuno\'s sophomore": [["Tanaka", "Nishinoya", "Chikara"]],
    "\"Guardian Deity\" and \"Ace\"": [["Nishinoya", "Asahi"]],
    "Leaders Cut from the Same Cloth":[["Daichi", "Kuroo"]],
    "Surprising Friendship":[["Aone", "Hinata"]],
    "Karasuno\'s Wing Spiker":[["Tanaka","Asahi","Chikara"]],//verify this one later on since 3 Wspikers
    "Teammates on the Court":[["Hinata", "Kageyama"]],
    "Simulated Junior Training Teamate":[["Kanji","Tsukishima"]],
    "Karasuno\'s Pillar(practice)": [["Chikara R", "Daichi SR"]],
    "\"Shield\" and \"Spear\"(practice)": [["Tsukishima SR", "Tadashi R"]],
    "Formidable Opponent" : [["Nishinoya", "Yaku"]],
    "Bench cheer": [["Hisashi", "Kazuhito"]],
    "The Returning Trio": [["Hisashi","Kazuhito","Chikara"]],
    "\"Sun\" and \"Moon\"": [["Tsukishima", "Hinata"]],
    "Building Team Chemistry": [["Tanaka", "Kageyama"]],
    "Karasuno\'s Sophomore(practice)": [["Tanaka SR", "Nishinoya SR", "Chikara R"]],
    "Rival Friends": [["Kenma","Hinata"]],
    "Behind the Smile": [["Daichi","Kuroo"]],
    "Master and Apprentice": [["Tsukishima","Kuroo"]],
    "Weird Duo": [["Hinata","Kageyama"]],
    "The King and The Great King": [["Kageyama","Oikawa"]],//double setter
    "Karasuno's Setters": [["Kageyama","Sugawara"]],// double setter
    "Karasuno's Failing Grades Group": [["Hinata","Kageyama","Nishinoya","Tanaka"]],
    "Team's Guardians": [["Nishinoya","Yaku"]],
    "Similar Builds": [["Hinata","Hoshiumi"]],
    "Weird Duo (Hanami)": [["Hinata","Kageyama"]],

    "Aoba Johsai's Sophomore":[["Watari", "Yahaba", "Kentaro"]],
    "Blunt and Composed":[["Kindaichi", "Kunimi"]],
    "The Wolf Pack":[["Kindaichi", "Kunimi"]],
    "Hidden Fire":[["Kentaro", "Yahaba"]],
    "Seijoh\'s Senior Year Pillars":[["Matsukawa", "Hanamaki"]],
    "The Wolf Pack(Practice)":[["Iwaizumi", "Kentaro"]],
    "Team Chemistry":[["Oikawa", "Iwaizumi"]],

    "Nekoma\'s Junior":[["Teshiro", "Inuoka","Lev"]],
    "\"Brain\" and \"Control Tower\"":[["Kenma", "Kuroo"]],
    "Nekoma\'s Wing Spiker":[["Ifukunaga", "Kai","Yamamoto"]],
    "Grit and Competitive":[["Kenma", "Yamamoto"]],
    "One-on-One Training":[["Lev", "Yaku"]],
    "The \"Enigmatic\" Teammate":[["Kenma", "Lev"]],
    "\"Pivot\" and \"Defensive Pivot\"":[["Kenma", "Yaku"]],
    "\"Pivot\" and \"Control Tower\"":[["Kenma", "Kuroo"]],
    
    "Date Kogyo\'s Captains":[["Kenji","Kaname"]],
    "The Silent and the Snarky":[["Aone","Kenji"]],
    "New Captain \& Tall Rookie":[["Kenji","Kanji"]],
    "Date Kogyo\'s Wing Spiker": [["Yutaka","Takehito"]],
    "Date Kogyo\'s Setter":[["Kanji","Kaname"]],
    "Date Kogyo\'s Junior": [["Jingo","Sakunami"]],
    "Date Kogyo\'s Senior": [["Takehito"," Kaname","Kamasaki"]]
};

window.characters = characters;
window.synergyDescriptions = synergyDescriptions;
window.synergyMeta = synergyMeta;
window.synergyPairs = synergyPairs;