// template: { name: "", role: "", img: "img-global/", school: "", bonds: [] },
const characters = [
    { name: "Hinata SSR", role: "MB", img: "img-global/hinataSSR.png", school: "Karasuno", bonds: ["Flexible Aces", "Worthy Rival", "Surprising Friendship"] },
    { name: "Hinata SR", role: "MB", img: "img-global/hinataSR.png", school: "Karasuno", bonds: ["Teammates on the Court","\"Sun\" and \"Moon\""] },
    { name: "Kageyama SSR", role: "S", img: "img-global/tobioSSR.png", school: "Karasuno", bonds: ["Teammates on the Court","Building Team Chemistry"] },
    { name: "Daichi SSR", role: "OP", img: "img-global/daichiSSR.png", school: "Karasuno", bonds: ["Karasuno\'s Pillar","karasuno Senior Year"] },
    { name: "Daichi SR", role: "OP", img: "img-global/daichiSR.png", school: "Karasuno", bonds: ["Karasuno\'s Pillar(practice)","Leaders Cut from the Same Cloth"] },
    { name: "Sugawara SR", role: "S", img: "img-global/sugawaraSR.png", school: "Karasuno", bonds: ["karasuno Senior Year",] },
    { name: "Asahi SSR", role: "WS", img: "img-global/asahiSSR.png", school: "Karasuno", bonds: ["karasuno Senior Year","\"Guardian Deity\" and \"Wing Spiker\"","Cannon \& Iron Wall"] },
    { name: "Asahi SR", role: "WS", img: "img-global/asahiSR.png", school: "Karasuno", bonds: ["\"Guardian Deity\" and \"Ace\"","Karasuno\'s Wing Spiker"] },
    { name: "Nishinoya SSR", role: "Li", img: "img-global/nishinoyaSSR.png", school: "Karasuno", bonds: ["Karasuno\'s sophomore", "Kiyoko\'s Knights","\"Guardian Deity\" and \"Wing Spiker\""] },
    { name: "Nishinoya SR", role: "Li", img: "img-global/nishinoyaSR.png", school: "Karasuno", bonds: ["\"Guardian Deity\" and \"Ace\"","Formidable Opponent","Karasuno\'s Sophomore(practice)"] },
    { name: "Tanaka SSR", role: "WS", img: "img-global/tanakaSSR.png", school: "Karasuno", bonds: ["Karasuno\'s sophomore", "Kiyoko\'s Knights","TOMODACHI(Friends!)"] },
    { name: "Tanaka SR", role: "WS", img: "img-global/tanakaSR.png", school: "Karasuno", bonds: ["Karasuno\'s Wing Spiker","Building Team Chemistry","Karasuno\'s Sophomore(practice)"] },
    { name: "Tsukishima SSR", role: "MB", img: "img-global/tsukishimaSSR.png", school: "Karasuno", bonds: ["\"Shield\" and \"Spear\"",] },
    { name: "Tsukishima SR", role: "MB", img: "img-global/tsukishimaSR.png", school: "Karasuno", bonds: ["Simulated Junior Training Teamate","\"Shield\" and \"Spear\"(practice)","\"Sun\" and \"Moon\""] },
    { name: "Tadashi SR", role: "MB", img: "img-global/tadashiSR.png", school: "Karasuno", bonds: ["\"Shield\" and \"Spear\"",] },
    { name: "Tadashi R", role: "MB", img: "img-global/tadashiR.png", school: "Karasuno", bonds: ["\"Shield\" and \"Spear\"(practice)"] },
    { name: "Chikara SR", role: "WS", img: "img-global/chikaraSR.png", school: "Karasuno", bonds: ["Karasuno\'s sophomore", "Karasuno\'s Pillar","The Returning Trio"] },
    { name: "Chikara R", role: "WS", img: "img-global/chikaraR.png", school: "Karasuno", bonds: ["Karasuno\'s Wing Spiker","Karasuno\'s Pillar(practice)","Karasuno\'s Sophomore(practice)"] },
    { name: "Hisashi R", role: "WS", img: "img-global/hisashiR.png", school: "Karasuno", bonds: ["Bench cheer","The Returning Trio"] },
    { name: "Kazuhito R", role: "MB", img: "img-global/kazuhitoR.png", school: "Karasuno", bonds: ["Bench cheer","The Returning Trio"] },
    { name: "Kageyama SR", role: "S", img: "img-global/tobioSR.png", school: "Kitagawa", bonds: [] },

    { name: "Oikawa SSR", role: "S", img: "img-global/oikawaSSR.png", school: "Aoba Johsai", bonds: [] },
    { name: "Iwaizumi SSR", role: "WS", img: "img-global/iwaizumiSSR.png", school: "Aoba Johsai", bonds: [] },
    { name: "Iwaizumi SR", role: "WS", img: "img-global/iwaizumiSR.png", school: "Aoba Johsai", bonds: [] },
    { name: "Matsukawa SR", role: "MB", img: "img-global/matsukawaSR.png", school: "Aoba Johsai", bonds: [] },
    { name: "Hanamaki SR", role: "WS", img: "img-global/hanamakiSR.png", school: "Aoba Johsai", bonds: [] },
    { name: "Yahaba SR", role: "S", img: "img-global/yahabaSR.png", school: "Aoba Johsai", bonds: [] },
    { name: "Watari SR", role: "Li", img: "img-global/watariSR.png", school: "Aoba Johsai", bonds: [] },
    { name: "Kindaichi SR", role: "MB", img: "img-global/kindaichiSR.png", school: "Aoba Johsai", bonds: [] },
    { name: "Kunimi SR", role: "OP", img: "img-global/kunimiSR.png", school: "Aoba Johsai", bonds: [] },
    { name: "Kentaro SSR", role: "OP", img: "img-global/kyotaniSSR.png", school: "Aoba Johsai", bonds: [] },
    { name: "Kentaro SR", role: "OP", img: "img-global/kyotaniSR.png", school: "Aoba Johsai", bonds: [] },

    //{ name: "Kenma SSR", role: "S", img: "img-global/kenmaSSR.png", school: "Nekoma", bonds: [] },
    { name: "Kenma SR", role: "S", img: "img-global/kenmaSR.png", school: "Nekoma", bonds: [] },
    //{ name: "Kuroo UR", role: "MB", img: "img-global/kurooUR.png", school: "Nekoma", bonds: [""] },
    { name: "Kuroo SSR", role: "MB", img: "img-global/kurooSSR.png", school: "Nekoma", bonds: ["Leaders Cut from the Same Cloth"] },
    { name: "Yaku SR", role: "Li", img: "img-global/yakuSR.png", school: "Nekoma", bonds: ["Formidable Opponent"] },
    { name: "Lev SSR", role: "MB", img: "img-global/levSSR.png", school: "Nekoma", bonds: ["Flexible Aces"] },
    { name: "Lev SR", role: "MB", img: "img-global/levSR.png", school: "Nekoma", bonds: [] },
    { name: "Yamamoto SR", role: "WS", img: "img-global/yamamotoSR.png", school: "Nekoma", bonds: ["TOMODACHI(Friends!)"] },
    { name: "Kai SR", role: "OP", img: "img-global/kaiSR.png", school: "Nekoma", bonds: [] },
    { name: "Fukunaga SR", role: "WS", img: "img-global/fukunagaSR.png", school: "Nekoma", bonds: [] },
    { name: "Inuoka SR", role: "MB", img: "img-global/inuokaSR.png", school: "Nekoma", bonds: ["Worthy Rival"] },
    { name: "Teshiro SR", role: "S", img: "img-global/teshiroSR.png", school: "Nekoma", bonds: [] },

    { name: "Aone SSR", role: "MB", img: "img-global/aoneSSR.png", school: "Date Kogyo", bonds: ["Cannon \& Iron Wall","Surprising Friendship"] },
    { name: "Aone SR", role: "MB", img: "img-global/aoneSR.png", school: "Date Kogyo", bonds: [] },
    { name: "Kenji SSR", role: "WS", img: "img-global/kenjiSSR.png", school: "Date Kogyo", bonds: [] },
    { name: "Kenji SR", role: "WS", img: "img-global/kenjiSR.png", school: "Date Kogyo", bonds: [] },
    { name: "Kanji SSR", role: "S", img: "img-global/kanjiSSR.png", school: "Date Kogyo", bonds: [] },
    { name: "Kanji SR", role: "S", img: "img-global/kanjiSR.png", school: "Date Kogyo", bonds: ["Simulated Junior Training Teamate"] },
    { name: "Sakunami R", role: "Li", img: "img-global/sakunamiR.png", school: "Date Kogyo", bonds: [] },
    { name: "Kamasaki SR", role: "MB", img: "img-global/kamasakiSR.png", school: "Date Kogyo", bonds: [] },
    { name: "Kaname SR", role: "S", img: "img-global/kanameSR.png", school: "Date Kogyo", bonds: [] },
    { name: "Sasaya SSR", role: "OP", img: "img-global/takehitoSSR.png", school: "Date Kogyo", bonds: [] },
    { name: "Sasaya SR", role: "OP", img: "img-global/takehitoSR.png", school: "Date Kogyo", bonds: [] },
    { name: "Yutaka SR", role: "WS", img: "img-global/yutakaSR.png", school: "Date Kogyo", bonds: [] },
    { name: "Jingo R", role: "MB", img: "img-global/jingoR.png", school: "Date Kogyo", bonds: [] },
    { name: "Taro R", role: "OP", img: "img-global/taroR.png", school: "Date Kogyo", bonds: [] },

    { name: "Ushijima UR", role: "OP", img: "img-global/ushijimaUR.png", school: "Shiratorizawa", bonds: [] },
    { name: "Taichi SR", role: "MB", img: "img-global/kawanishiSR.png", school: "Shiratorizawa", bonds: [] },
];
// tempalte: "": "",
const synergyDescriptions = {
    "Karasuno": "Increases Power Attack and Quick Attack stats of all players present by 10%",
    "Shiratorizawa": "Increases Awareness and Strength of all players present by 10%",
    "Aoba Johsai": "Increases Power Attack stats of all players present by 15%",
    "Nekoma": "Increases Receive stat of all players present by 15%",
    "Date Kogyo": "Increases Block stat of all players present by 15%",

    //karasuno bond
    "Karasuno\'s Pillar": "When achieving a PERFECT receive, increases Team Morale by 3/3/4/4/5",
    "Flexible Aces": { "Hinata SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%", "Lev SSR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%"},
    "Worthy Rival": {"Hinata SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Inuoka SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},
    "Kiyoko\'s Knights": "When scoring, increases Team morale by 6/7/8/9/10",
    "karasuno Senior Year": "Reduces Stamina consumption of Spike skills by 10%; when performing Power Spikes, increases this player\'s Attack Technique by 6/7/8/9/10%",
    "\"Guardian Deity\" and \"Wing Spiker\"": "When Nishinoya or Asahi casts a skill, increases their Attack Technique and Defense Technique by 6/7/8/9/10%",
    "\"Shield\" and \"Spear\"":"Increases Tsukishima\'s Block stat by 6/7/8/9/10% and Tadashi\'s Serve stat by 6/7/8/9/10%",
    "TOMODACHI(Friends!)":{"Yamamoto SR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%","Tanaka SSR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "Cannon \& Iron Wall": {"Asahi SSR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%","Aone SSR":"No buff"},
    "Karasuno\'s sophomore": {"Chikara SR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%", "Nishinoya SSR": "Set +5/7/9/12/15, Set +1/2/3/4/5%", "Tanaka SSR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "\"Guardian Deity\" and \"Ace\"":"When Nishinoya or Asahi casts a skill, increases their Attack Technique by 6/7/8/9/10%",
    "Leaders Cut from the Same Cloth": {"Daichi SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Kuroo SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Surprising Friendship":{"Aone SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Hinata SSR":"No buff"},
    "Karasuno\'s Wing Spiker":{"Tanaka SR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%", "Asahi SR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%", "Chikara SR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "Teammates on the Court": "When casting Quick Spike skills, increases this player's Awareness ny 6/7/8/9/10%",
    "Simulated Junior Training Teamate": {"Kanji SR":"Set +5/7/9/12/15, Set +1/2/3/4/5%","Tsukishima SR": "No buff"},
    "Karasuno\'s Pillar(practice)": {"Chikara R": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Daichi SR":"Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "\"Shield\" and \"Spear\"(practice)": "Increases Tsukishima\'s Block stat by 6/7/8/9/10% and Tadashi\'s Serve stat by 6/7/8/9/10%",
    "Formidable Opponent": {"Nishinoya SR":" Save +5/7/9/12/15, Save +1/2/3/4/5%","Yaku SR":" Set +5/7/9/12/15, Set +1/2/3/4/5%"},
    "Bench cheer" : {"Hisashi R": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%", "Kazuhito R": "Block +5/7/9/12/15, Block +1/2/3/4/5%" },
    "The Returning Trio":{"Hisashi R":"Set +5/7/9/12/15, Set +1/2/3/4/5%","Kazuhito R":"Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%","Chikara SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},
    "\"Sun\" and \"Moon\"": {"Tsukishima SR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%", "Hinata SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%" },
    "Building Team Chemistry": {"Kageyama SSR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%", "Tanaka SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%" },
    "Karasuno\'s Sophomore(practice)":"Increases Receive stat of back row players 6/7/8/9/10%",

    "Aoba Johsai's Sophomore": {}

};

//Lowkey just have to remeber that when a bond is create I put it here
//template: "": { category: "school| stats|deployement", activation: { scope: "starters|any", min:  } },
const synergyMeta = {
    "Karasuno": { category: "school", activation: { scope: "starters", min: 4 } },
    "Shiratorizawa": { category: "school", activation: { scope: "starters", min: 4 } },
    "Aoba Johsai": { category: "school", activation: { scope: "starters", min: 4 } },
    "Nekoma": { category: "school", activation: { scope: "starters", min: 4 } },
    "Date Kogyo": { category: "school", activation: { scope: "starters", min: 4 } },

    "Karasuno\'s Pillar": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Flexible Aces": { category: "stats", activation: { scope: "any", min: 2 } },
    "Worthy Rival": { category: "stats", activation: { scope: "any", min: 2 } },
    "Kiyoko\'s Knights": { category: "deployment", activation: { scope: "any", min: 2 } },
    "karasuno Senior Year": { category: "deployment", activation: { scope: "any", min: 3 } },
    "\"Guardian Deity\" and \"Wing Spiker\"":{ category: "deployment", activation: { scope: "any", min: 2 } },
    "\"Shield\" and \"Spear\" (practice)":{ category: "deployment", activation: { scope: "any", min: 2 } },
    "TOMODACHI(Friends!)":{ category: "stats", activation: { scope: "any", min: 2 } },
    "Cannon \& Iron Wall":{ category: "stats", activation: { scope: "any", min: 2 } },
    "Karasuno\'s sophomore": { category: "stats", activation: { scope: "any", min: 3 } },
    "\"Guardian Deity\" and \"Ace\"": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Leaders Cut from the Same Cloth": { category: "stats", activation: { scope: "any", min: 2 } },
    "Surprising Friendship": { category: "stats", activation: { scope: "any", min: 2 } },
    "Karasuno\'s Wing Spiker": { category: "stats", activation: { scope: "any", min: 3 } },
    "Teammates on the Court": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Simulated Junior Training Teamate": { category: "stats", activation: { scope: "any", min: 2 } },
    "Karasuno\'s Pillar(practice)": { category: "stats", activation: { scope: "any", min: 2 } },
    "\"Shield\" and \"Spear\"(practice)": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Formidable Opponent": { category: "stats", activation: { scope: "any", min: 2 } },
    "Bench cheer": { category: "stats", activation: { scope: "any", min: 2 } },
    "The Returning Trio": { category: "stats", activation: { scope: "any", min: 3 } },
    "\"Sun\" and \"Moon\"": { category: "stats", activation: { scope: "any", min: 2 } },
    "Building Team Chemistry": { category: "stats", activation: { scope: "any", min: 2 } },
    "Karasuno\'s Sophomore(practice)": { category: "deployment", activation: { scope: "any", min: 3 } },
};

//put what player create the bond
const synergyPairs = {
    "Karasuno\'s Pillar": [["Chikara", "Daichi"]],
    "Flexible Aces": [["Hinata", "Lev"]],
    "Worthy Rival": [["Hinata", "Inuoka"]],
    "Kiyoko\'s Knights": [["Tanaka", "Nishinoya"]],
    "karasuno Senior Year": [["Daichi", "Sugawara", "Asahi"]],
    "\"Guardian Deity\" and \"Wing Spiker\"": [["Nishinoya", "Asahi"]],
    "\"Shield\" and \"Spear\"": [["Tsukishima", "Tadashi"]],
    "TOMODACHI(Friends!)":[["Tanaka","Yamamoto"]],
    "Cannon \& Iron Wall":[["Asahi", "Aone"]],
    "Karasuno\'s sophomore": [["Tanaka", "Nishinoya", "Chikara"]],
    "\"Guardian Deity\" and \"Ace\"": [["Nishinoya", "Asahi"]],
    "Leaders Cut from the Same Cloth":[["Daichi", "Kuroo"]],
    "Surprising Friendship":[["Aone", "Hinata"]],
    "Karasuno\'s Wing Spiker":[["Tanaka","Asahi","Chikara"]],//verify this one later on since 3 Wspikers
    "Teammates on the Court":[["Hinata", "Kageyama"]],
    "Simulated Junior Training Teamate":[["Kanji","Tsukishima"]],
    "Karasuno\'s Pillar(practice)": [["Chikara R", "Daichi SR"]],
    "\"Shield\" and \"Spear\"(practice)": [["Tsukishima SR", "Tadashi R"]],
    "Formidable Opponent" : [["Nishinoya", "Yaku"]],
    "Bench cheer": [["Hisashi", "Kazuhito"]],
    "The Returning Trio": [["Hisashi","Kazuhito","Chikara"]],
    "\"Sun\" and \"Moon\"": [["Tsukishima", "Hinata"]],
    "Building Team Chemistry": [["Tanaka", "Kageyama"]],
    "Karasuno\'s Sophomore(practice)": [["Tanaka SR", "Nishinoya SR", "Chikara R"]],
};

window.characters = characters;
window.synergyDescriptions = synergyDescriptions;
window.synergyMeta = synergyMeta;
window.synergyPairs = synergyPairs;