const characters = [
    { name: "Kageyama UR", role: "S", img: "img-japan/kageyamaUR.png", school: "Karasuno", bonds: ["Eccentric Duo", "Karasuno Geniuses"] },
    { name: "Koganegawa SSR", role: "S", img: "img-japan/koganegawaSR.png", school: "Dateko", links: ["The New Captain and the Tall Rookie"] },
    { name: "Kageyama SSR", role: "S", img: "img-japan/kageyamaSR.png", school: "Karasuno", bonds: ["NA"] },
    { name: "Sugawara SP", role: "S", img: "img-japan/sugawaraSP.png", school: "Karasuno", links: ["After School"] },
    { name: "Kenma SP", role: "S", img: "img-japan/kenmaSP.png", school: "Nekoma", links: ["Cherry Blossom Viewing"] },
    { name: "Kenma SSR", role: "S", img: "img-japan/kenmaSR.png", school: "Nekoma", links: ["Brain and Commander"] },
    { name: "Oikawa UR", role: "S", img: "img-japan/oikawaUR.png", school: "Aoba Johsai", links: ["Perfect Harmony"] },
    { name: "Oikawa SSR", role: "S", img: "img-japan/oikawaSR.png", school: "Aoba Johsai", links: ["NA"] },
    { name: "Shirabu SSR", role: "S", img: "img-japan/shirabuSR.png", school: "Shiratorizawa", links: ["Absolute Champion and Steady Setter"] },
    { name: "Semi SSR", role: "S", img: "img-japan/semiSR.png", school: "Shiratorizawa", links: ["NA"] },
    { name: "Akaashi SP", role: "S", img: "img-japan/akaashiSP.png", school: "Fukurodani", links: ["Swimming", "Ace Miraculous and Caring Setter"] },
    { name: "Akaashi SSR", role: "S", img: "img-japan/akaashiSR.png", school: "Fukurodani", links: ["Miracle Ace and Caring Setter"] },
    { name: "Atsumu UR", role: "S", img: "img-japan/atsumuUR.png", school: "Inarizaki", links: ["Twin Power", "Twin Heads"] },

    { name: "Tsukishima SP", role: "MB", img: "img-japan/tsukiSP.png", school: "Karasuno", bonds: ["Sun vs Moon"] },
    { name: "Tsukishima SSR", role: "MB", img: "img-japan/tsukiSR.png", school: "Karasuno", bonds: ["NA"] },
    { name: "Hinata SP", role: "MB", img: "img-japan/hinataSP.png", school: "Karasuno", bonds: ["Eccentric Duo", "Cherry Blossom Viewing", "Sun vs Moon"] },
    { name: "Hinata SSR", role: "MB", img: "img-japan/hinataSR.png", school: "Karasuno", bonds: ["Eccentric Duo"] },
    { name: "Kuro SSR", role: "MB", img: "img-japan/kuroSR.png", school: "Nekoma", links: ["NA"] },
    { name: "Kuro UR", role: "MB", img: "img-japan/kuroUR.png", school: "Nekoma", links: ["Brain and Commander"] },
    { name: "Lev SSR", role: "MB", img: "img-japan/levSR.png", school: "Nekoma", links: ["Educational Guidance"] },
    { name: "Aone SP", role: "MB", img: "img-japan/aoneSP.png", school: "Dateko", links: ["Swimming"] },
    { name: "Aone SSR", role: "MB", img: "img-japan/aoneSR.png", school: "Dateko", links: ["The Silent and the Sarcastic"] },
    { name: "Tendo SSR", role: "MB", img: "img-japan/tendoSR.png", school: "Shiratorizawa", links: ["Besties for Life"] },
    { name: "Rintaro SSR", role: "MB", img: "img-japan/rintaroSR.png", school: "Inarizaki", links: ["NA"] },
    { name: "Hirugami UR", role: "MB", img: "img-japan/hirugamiUR.png", school: "Kamomedai", links: ["Longtime Friends"] },
    { name: "Tatsuo SSR", role: "MB", img: "img-japan/tatsuoSR.png", school: "Fukurodani", links: ["NA"] },

    { name: "Tanaka SSR", role: "WS", img: "img-japan/tanakaSR.png", school: "Karasuno", bonds: ["Kiyoko Squad"] },
    { name: "Futakuchi SSR", role: "WS", img: "img-japan/futakuchiSR.png", school: "Dateko", links: ["The Silent and the Sarcastic", "The New Captain and the Tall Rookie"] },
    { name: "Azumane SSR", role: "WS", img: "img-japan/azumaneSR.png", school: "Karasuno", links: ["Guardian God and Wing Spiker"] },
    { name: "Kita SSR", role: "WS", img: "img-japan/kitaSR.png", school: "Inarizaki", links: ["Twin Heads"] },
    { name: "Terushima SSR", role: "WS", img: "img-japan/terushimaSR.png", school: "Jozenji", links: ["NA"] },
    { name: "Goshiki SSR", role: "WS", img: "img-japan/goshikiSR.png", school: "Shiratorizawa", links: ["Shiratorizawa’s WS"] },
    { name: "Ohira SSR", role: "WS", img: "img-japan/ohiraSR.png", school: "Shiratorizawa", links: ["Shiratorizawa’s WS"] },
    { name: "Bokuto UR", role: "WS", img: "img-japan/bokutoUR.png", school: "Fukurodani", links: ["Miracle Ace and Caring Setter"] },
    { name: "Bokuto SP", role: "WS", img: "img-japan/bokutoSP.png", school: "Fukurodani", links: ["Swimming", "Ace Miraculous and Caring Setter"] },
    { name: "Oshiro SSR", role: "WS", img: "img-japan/oshiroSR.png", school: "Inarizaki", links: ["NA"] },
    { name: "Yui SSR", role: "WS", img: "img-japan/yuiSR.png", school: "Inarizaki", links: ["NA"] },
    { name: "Hoshiumi UR", role: "WS", img: "img-japan/hoshiumiUR.png", school: "Kamomedai", links: ["Longtime Friends"] },
    { name: "Hayaseiomi UR", role: "WS", img: "img-japan/hayaseiomiUR.png", school: "Itachiyama", links: ["Top Spiker and Top Libero"] },
    { name: "Iwazumi SSR", role: "WS", img: "img-japan/iwazumiSR.png", school: "Aoba Johsai", links: ["Perfect Harmony", "The Pack"] },

    { name: "Nishinoya SP", role: "L", img: "img-japan/nishinoyaSP.png", school: "Karasuno", bonds: ["Karasuno Geniuses", "After School"] },
    { name: "Nishinoya SSR", role: "L", img: "img-japan/nishinoyaSR.png", school: "Karasuno", bonds: ["Guardian God and Wing Spiker", "Kiyoko Squad"] },
    { name: "Yaku SSR", role: "L", img: "img-japan/yakuSR.png", school: "Nekoma", links: ["Educational Guidance"] },
    { name: "Yamagata SSR", role: "L", img: "img-japan/yamagataSR.png", school: "Shiratorizawa", links: ["NA"] },
    { name: "Haruki SSR", role: "L", img: "img-japan/harukiSR.png", school: "Fukurodani", links: ["NA"] },
    { name: "Akagi SSR", role: "L", img: "img-japan/akagiSR.png", school: "Inarizaki", links: ["NA"] },
    { name: "Komori UR", role: "L", img: "img-japan/komoriUR.png", school: "Itachiyama", links: ["Top Spiker and Top Libero"] },

    { name: "Daichi SSR", role: "OP", img: "img-japan/daichiSR.png", school: "Karasuno", bonds: ["NA"] },
    { name: "Sasaya SSR", role: "OP", img: "img-japan/sasayaSR.png", school: "Dateko", links: ["NA"] },
    { name: "Kentaro MAD DOG SSR", role: "OP", img: "img-japan/kentaroSR.png", school: "Aoba Johsai", links: ["The Pack"] },
    { name: "Ushijima UR", role: "OP", img: "img-japan/ushijimaUR.png", school: "Shiratorizawa", links: ["Besties for Life", "Absolute Champion and Steady Setter"] },
    { name: "Konoha SSR", role: "OP", img: "img-japan/konohaSR.png", school: "Fukurodani", links: ["NA"] },
    { name: "Osamu UR", role: "OP", img: "img-japan/osamuUR.png", school: "Inarizaki", links: ["Twin Power", "Twin Heads"] },
];

const synergyDescriptions = {
    "Karasuno": "Increases ALL players’ Power Attack and Quick Attack stats by 10%",
    "Nekoma": "Increases ALL players’ Receive stat by 15%",
    "Dateko": "Increases ALL players’ Block stat by 15%",
    "Aoba Johsai": "Increases ALL players’ Power Attack stat by 15%",
    "Shiratorizawa": "Increases ALL players’ Awareness and Strength stats by 10%",
    "Fukurodani": "Team Morale increases by 20",
    "Inarizaki": "Increases ALL players’ Strength and Defense stats by 5%",
    "Eccentric Duo": "Increases Hinata and Kageyama’s quick attack power and Awareness.",
    "Karasuno Geniuses": "Increases Nishinoya SP’s reflex and Receive. When Nishinoya uses his special move, Kageyama UR gains one stack of Competitive Spirit*. If his special is perfect, the first spike (Power or Quick Attack) after that play is increased by 20% of the attacker’s power.",
    "Cherry Blossom Viewing": "Increases Kenma SP’s Awareness. Increases Hinata SP’s Quick Attack if it is a perfect play.",
    "Sun vs Moon": "No info available.",
    "After School": "Increases Nishinoya SP’s reflex; further increased when stamina is low.",
    "Guardian God and Wing Spiker": "When Nishinoya SSR or Azumane SSR use a skill, both increase their Attack Technique and Defense Technique.",
    "Kiyoko Squad": "When scoring, increases Team Morale.",
    "Brain and Commander": "When Kenma SSR makes a pass, Kuro UR performs a strengthened Quick Attack.",
    "Educational Guidance": "Increases Yaku SSR’s Receive and Lev SSR’s Quick Attack.",
    "Swimming": "(Activates with 3 players) Increases team morale. When active, increases allies’ reflex in double or triple blocks.",
    "The Silent and the Sarcastic": "Allows Aone SSR and Futakuchi SSR to use the Double Block skill.",
    "The New Captain and the Tall Rookie": "Increases the Block of players in the front row.",
    "Perfect Harmony": "When Oikawa UR makes a pass, Iwaizumi SSR spikes with increased Power Attack. Gains 2 stacks of Attack Rhythm*, each increasing team Awareness by 1%, max 10 stacks.",
    "The Pack": "Increases Power Attack of Iwaizumi SSR and Kentaro SSR.",
    "Besties for Life": "Increases Ushijima UR’s Power Attack and Tendo SSR’s Defense Technique.",
    "Absolute Champion and Steady Setter": "When Shirabu SSR makes a pass, Ushijima UR spikes with 10% more power.",
    "Shiratorizawa’s WS": "Increases Power Attack of ALL players present.",
    "Miracle Ace and Caring Setter": "Bokuto UR recovers from depression. When Akaashi SSR makes a pass and Bokuto UR spikes, increases that spike’s Power Attack by 20% and raises team morale by 15.",
    "Ace Miraculous and Caring Setter": "Increases Akaashi SP’s Passing. When morale is active, increases Bokuto SP’s Power Attack by 18% and Akaashi SP’s Passing by 5%.",
    "Twin Power": "When Atsumu UR passes and Osamu UR does a Minus Tempo Quick Attack, increases that play’s Quick Attack and Attack Technique by 15%. Cannot be blocked.",
    "Twin Heads": "Increases Osamu UR’s Attack Technique and Kita SSR’s stats. Atsumu gains Perfect Hit stacks, each increasing Passing by 2% (max 10). Kita SSR gains Receive stacks (max 3). Twins’ first Quick Attack per set is increased by Quick Attack × 12%.",
    "Longtime Friends": "Increases Hoshiumi UR’s stats and front-row players’ Block. Grants Hoshiumi UR and Hirugami UR a buff (no info).",
    "Top Spiker and Top Libero": "Sakusa UR increases Power Attack. Komori UR increases Receive. Increases allies’ Receive by 20%.",
};
